spring:
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  messages:
    basename: messages

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id:  ${KAFKA_NOTIFICATIONS_GROUP_ID:notification-group}
    topics:
      comment-topic:
        name: ${KAFKA_NOTIFICATION_COMMENT_TOPIC:notification_comment_topic}
      like-topic:
        name: ${KAFKA_NOTIFICATION_LIKE_TOPIC:notification_like_topic}
      event-start-topic:
        name: ${KAFKA_EVENT_START_TOPIC:event_start_topic}

telegram:
  bot:
    username: ${TELEGRAM_BOT_NAME:@CorporationX_notifi_bot}
    token: ${TELEGRAM_BOT_TOKEN:}

  messages:
    basename: messages

server:
  port: ${NOTIFICATION_SERVICE_PORT:8083}

logging:
  level:
    root: info
    liquibase: info
    org.testcontainers: info

vonage: #https://dashboard.nexmo.com/getting-started/sms
  api:
    key: ${VONAGE_API_KEY:}
    secret: ${VONAGE_API_SECRET:}
    from: ${VONAGE_API_SENDER:Vonage Api}

user-service:
  host: ${USER_SERVICE_HOST:localhost}
  port: ${USER_SERVICE_PORT:8080}  
